# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_wlm <- function(X, y, freqs) {
    .Call(`_blblm_fast_wlm`, X, y, freqs)
}

